# Generated by Django 6.0.3 on 2026-04-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_resume_contact_email_resume_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_interview_questions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='match_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='resume',
            name='parsed_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
