# Generated by Django 6.0.3 on 2026-04-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_application_ai_interview_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview', 'Interviewing'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
    ]
